### ISSUE TITLE
Pessoa Jurídica - CNPJ não copiando para "Taxvat Number"

### ISSUE THREAD

**Issue by guiserinoli** [eduardoddias/Magento-SystemCode_BrazilCustomerAttributes#1]
Quando é realizado cadastro de pessoa jurídica, o CNPJ não está sendo copiado para o Número de Tax/VAT.

**Comment by eduardoddias** [comment]
@guiserinoli, obrigado por reportar, consegui simular aqui será corrigido essa semana.

**Comment by guiserinoli** [comment]
A correção que enviei apresenta problemas, então fico no aguardo de uma nova correção do módulo. Obrigado desde já!

**Comment by eduardoddias** [comment]
Entre hoje e amanhã estará disponível junto com uma melhoria no módulo e outras pequenas correções.

**Comment by eduardoddias** [comment]
@guiserinoli, corrigido. Obrigado ter reportado o bug.
