### ISSUE TITLE
The configuration parameter "formElement" is required for "cnpj" field.

### ISSUE THREAD

**Issue by sidneydeus** [eduardoddias/Magento-SystemCode_BrazilCustomerAttributes#10]
No admin, ao tentar ver as informações do cliente este erro apareceu. 
versão 2.2.3
![nmpdahhjbhanilgo-1](https://user-images.githubusercontent.com/6332716/46539897-2109c600-c88e-11e8-9634-7da3f9552ebf.png)

**Comment by eduardoddias** [comment]
Faz um backup do banco e tenta rodar esse comando:
update eav_attribute set backend_type='varchar', frontend_input='text' where attribute_code='cnpj';

Se não resolver, já recomendo que restaure o banco.

**Comment by sidneydeus** [comment]
Resolvido.
Porém foi preciso atualizar para os demais campos criados. (rg,ie,socialname,tradename e etc)
Valeu!Obrigado pela dica.
