### ISSUE TITLE
Funciona em qualquer template?

### ISSUE THREAD

**Issue by rafaelschaffer** [eduardoddias/Magento-SystemCode_BrazilCustomerAttributes#11]
Olá Eduardo, estou usando o template Krystal, no Magento 2.2.2.
Realizei a instalação e o módulo aparece no painel administrativo. Mas no ecommerce, não aparece o recurso CNPJ/CPF.
Ele aparece quando crio uma nova conta? No meu não aparece...
O mesmo ocorre ao editar uma conta, é como se o módulo não estivesse funcionando...

Você pode me ajudar?
Abs

**Comment by eduardoddias** [comment]
Pode ser que seu tema sobreescreva os mesmo templates que o módulo. Nesse caso o ideal seria criar um novo tema, "filho" do Krystal e mesclar o phtml do tema com o do módulo.
