### ISSUE TITLE
recomendo

### ISSUE THREAD

**Issue by wubuyun** [eduardoddias/Magento-SystemCode_BrazilCustomerAttributes#12]
primeira consulta autopreenchimeno de endereco do correios demora quase 4 minutos para conclui, recomendo mais um api da consulta.. com delay..

**Comment by eduardoddias** [comment]
Obrigado pela sugestão, foi adicionado no TODO do README. Será implementado em breve.

**Comment by wubuyun** [comment]
https://github.com/albertobraschi/Bleez-Correios/tree/438e0e1c4cada9bc3cc2a12e898a4ffa6d7063bf/Model/Endereco
