### ISSUE TITLE
Erro 500 zipcode

### ISSUE THREAD

**Issue by jhomoreira** [eduardoddias/Magento-SystemCode_BrazilCustomerAttributes#13]
Todas as lojas que utilizam o módulo recebem o erro `brcustomer/consult/address/zipcode/90020160?_=1541434496251 500`
Este erro ocorre quando inserido o CEP para consulta. 
Acredito que o mesmo aconteça para todos os usuários dos módulos pois para nós 5 projetos estão assim.

**Comment by josneyr** [comment]
Olá, conseguiram resolver esse erro?
/brcustomer/consult/address/zipcode/82100580?_=1541773494922 503

**Comment by jhomoreira** [comment]
@josneyr Sim já envie pull request com a correção.

**Comment by josneyr** [comment]
Funcionou.Obrigado!

**Comment by eduardoddias** [comment]
Obrigado, issue resolvida, estou fechando o bug.
