### ISSUE TITLE
Erro ao instalar o módulo

### ISSUE THREAD

**Issue by willianmenezes** [eduardoddias/Magento-SystemCode_BrazilCustomerAttributes#15]
tentei instalar o modulo e  está emitindo o seguinte erro, 

 [RuntimeException]
  Source class "\SystemCode\BrazilCustomerAttributes\Model\Magento\Customer\R
  esourceModel\AddressInterface" for "SystemCode\BrazilCustomerAttributes\Mod
  el\Magento\Customer\ResourceModel\AddressRepository" generation does not ex
  ist.

minha versão do magento é a 2.1.9 e o versão do PHP é a 7.0.32-2

Alguém enfrentou esse problema?

**Comment by eduardoddias** [comment]
Você rodou os comandos:
php bin/magento setup:di:compile
php bin/magento setup:upgrade

Depois da instalação?

**Comment by willianmenezes** [comment]
Boa tarde!

Atualizei a versão do magento para 2.2.7 e funcionou normalmente.
