### ISSUE TITLE
Limpar mascara no ajax de envio

### ISSUE THREAD

**Issue by zapcriativo** [eduardoddias/Magento-SystemCode_BrazilCustomerAttributes#19]
Boa noite!

Estou utilizando na loja um validador que mostra se o produto é entregue em determinada região ou não, e os cadastros das regiões são efetuados através de CEP sem hífen. Ao digitar o cep na página do checkout, não esta mais encontrando nenhum método de envio cadastrado devido ao hífen que está sendo passado no ajax da que o magento usa na estimativa do envio.

A minha duvida é, tem como na ação do mouse out do campo, passar o valor do CEP sem o hífen para o ajax que faz a cotação do métodos de envio?

<img width="1657" alt="captura de tela 2019-02-06 as 22 34 15" src="https://user-images.githubusercontent.com/7153803/52383185-73870900-2a5f-11e9-9374-c0e24a43235b.png">

**Comment by eduardoddias** [comment]
Isso não é uma issue do módulo e sim uma incompatibilidade com o módulo de método de envio, para tal não oferecemos suporte gratuito via GitHub, caso tenha interesse em contratar nosso serviços entre em contato via e-mail.
