### ISSUE TITLE
tem como mudar bairro para linha 4?

### ISSUE THREAD

**Issue by marcelowu** [eduardoddias/Magento-SystemCode_BrazilCustomerAttributes#2]
tem como mudar bairro para linha 4? meu modulo de pagamento so funciona com bairro na linha 4..

**Comment by eduardoddias** [comment]
Pelas configurações não, você teria que criar um módulo e alterar a label, similar ao que o módulo faz no arquivo:
SystemCode/BrazilCustomerAttributes/Model/Checkout/LayoutProcessorPlugin.php

Você também teria que informar para seu módulo rodar depois do BrazilCustomerAttributes no etc/module.xml

Ou, o que eu acho mais correto, extender o módulo de pagamento e alterar o mapeamento desses campos.

Não pretendo trazer uma funcionalidade desse tipo ao módulo, pois ao meu ver deveria ser uma configuração do método de pagamento.

**Comment by wubuyun** [comment]
consiqui fazer no checkout bairro na linha 4, mas ela grava nos dados com bairro na linha 3, ta uma ajuda..
