### ISSUE TITLE
Erro no autocompletar do endereço 

### ISSUE THREAD

**Issue by zapcriativo** [eduardoddias/Magento-SystemCode_BrazilCustomerAttributes#20]
Boa tarde!

Ao tentar efetuar uma busca de CEP, não esta completando o endereço. Sabe o que pode ser?

![captura de tela 2019-02-07 as 15 17 31](https://user-images.githubusercontent.com/7153803/52429665-a2e35780-2aeb-11e9-84f4-88350dc7c7e1.png)

**Comment by zapcriativo** [comment]
Consegui resolver, é necessário deixar habilitado o cache do magento.

**Comment by eduardoddias** [comment]
Não faz muito sentido, mas se resolveu ok.
