### ISSUE TITLE
Erro Forma de Pagamento

### ISSUE THREAD

**Issue by KovalskiWeb** [eduardoddias/Magento-SystemCode_BrazilCustomerAttributes#22]
Fiz um teste de compra com o módulo do PagSeguro e funcionou certinho, porém, testei com outro módulo de pagamento, e deu o seguinte erro:

dominio.com.br/rest/default/V1/carts/mine/payment-information 400 (Bad Request)
Uncaught TypeError: messageContainer.addErrorMessage is not a function

**Comment by eduardoddias** [comment]
Isso está relacionado ao módulo de pagamento e não ao módulo de pessoa física/jurídica.
