### ISSUE TITLE
licença é paga?

### ISSUE THREAD

**Issue by marcelowu** [eduardoddias/Magento-SystemCode_BrazilCustomerAttributes#23]

**Comment by marcelowu** [comment]
no composer como propritario

**Comment by marcelowu** [comment]
error aparece no campo de telefone

![2019-08-20 02-54-50屏幕截图](https://user-images.githubusercontent.com/30912144/63321417-09e19480-c2f7-11e9-9440-a28cc137cb2d.png)

**Comment by eduardoddias** [comment]
favor elaborar melhor suas questões.
