### ISSUE TITLE
Erro: Specified invalid parent id

### ISSUE THREAD

**Issue by KovalskiWeb** [eduardoddias/Magento-SystemCode_BrazilCustomerAttributes#28]
Não estou conseguindo acessar o back-end da minha loja, está dando esse erro após instalar esse módulo:

Log:
{"0":"Specified invalid parent id (SystemCode_Base::systemcode)","1":"<pre>#1 Magento\\Backend\\Model\\Menu\\Builder\\Interceptor->___callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\

**Comment by eduardoddias** [comment]
Você instalou o módulo SystemCode_Base como consta no README ?

**Comment by KovalskiWeb** [comment]
Eu tinha instalado baixando os arquivos na app/code...

Mas agora instalei pelo composer, e deu tudo certo! :)
