### ISSUE TITLE
CEP não autocompleta!

### ISSUE THREAD

**Issue by KovalskiWeb** [eduardoddias/Magento-SystemCode_BrazilCustomerAttributes#29]
Quando eu digito o CEP no carrinho de compras e prossigo para o checkout, na página do checkout os campos não vem preenchidos, só são autocompletados assim que eu passar pelo input do CEP.

**Comment by netembalagens** [comment]
Isto é uma funcionalidade que você deve implementar no seu checkout, 
Acredito que o modulo não salva o CEP para autocompletar os campos no checkout.

**Comment by eduardoddias** [comment]
Como o @netembalagens comentou, o módulo não contempla essa funcionalidade.
