### ISSUE TITLE
Erro ao compilar - Magento 2.2.4 #7

### ISSUE THREAD

**Issue by wurthmann** [eduardoddias/Magento-SystemCode_BrazilCustomerAttributes#32]
Ao compilar a instalação do magento ele retorna o erro 

[RuntimeException]                                                    
  Class Magento\Framework\Serialize\SerializerInterface does not exist 

A pasta Serialize nem existe na instalação do MAgento

Existe alguma solução pra isso?!

**Comment by eduardoddias** [comment]
Você pode tentar utilizar uma versão mais antiga do módulo (terá que instalar manualmente):
https://github.com/eduardoddias/Magento-SystemCode_BrazilCustomerAttributes/tree/54a127ef3c611f200b0ec9b0ce9520e136ce9e08

Mas recomendo que atualize o Magento.
