### ISSUE TITLE
Compatibilidade com php 7.3

### ISSUE THREAD

**Issue by robsoned** [eduardoddias/Magento-SystemCode_BrazilCustomerAttributes#33]
Atualmente no require do pacote `Magento-SystemCode_Base` está com `"php": "~5.6.0|7.0.2|7.0.4|~7.0.6|~7.1.0|~7.1.3|~7.2.0",`. Isso acaba gerando erro na instalação via composer. Pois o php 7.3 não está listado no require.

**Comment by eduardoddias** [comment]
@robsoned obrigado por notificar, realizei o ajuste.
