### ISSUE TITLE
Erro ao instalar modulo

### ISSUE THREAD

**Issue by hectorcanaimero** [eduardoddias/Magento-SystemCode_BrazilCustomerAttributes#34]
Bom dia, Eu instalei este módulo no magento **2.3** e funcionou perfeitamente, atualmente estou instalando na versão **2.3.3** e isso me dá o seguinte erro:

`
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'table.sales_order_address' doesn't exist, query was: DESCRIBE `sales_order_address``

**Comment by eduardoddias** [comment]
@hectorcanaimero, você está instalando na CE ou EE?

**Comment by eduardoddias** [comment]
"Community Edition" (CE) ou "Enterprise Edition" (EE)?
