### ISSUE TITLE
Erro Address linha 24.

### ISSUE THREAD

**Issue by gutomissiatto-git** [eduardoddias/Magento-SystemCode_BrazilCustomerAttributes#36]
Boa tarde a todos,
estou com o seguinte erro, Fatal error:  Interface 'Magento\Framework\App\Action\HttpGetActionInterface' not found in /home/srv/meudominio/vendor/systemcode/brazilcustomerattributes/Controller/Consult/Address.php on line 24.
Estou utilizando Magento 2.2.8.

**Comment by robsoned** [comment]
@gutomissiatto-git De fato, na versão 2.2.x do magento esse arquivo não existe.
![image](https://user-images.githubusercontent.com/18008565/68941615-23bf3600-0785-11ea-8299-14fefa03582a.png)

Diferente da versão 2.3.x
![image](https://user-images.githubusercontent.com/18008565/68941646-389bc980-0785-11ea-998b-8864f95202a0.png)

Na última versão do módulo, Address.php passa a implementar HttpGetActionInterface.
Sugiro você utilizar a versão 1.0.2 do módulo ou fazer o Upgrade da versão do Magento para versão 2.3.x
