### ISSUE TITLE
Campos Duplicados

### ISSUE THREAD

**Issue by JeffersonTeixeira** [eduardoddias/Magento-SystemCode_BrazilCustomerAttributes#41]
Estou utilizando a configuração abaixo:
![image](https://user-images.githubusercontent.com/23153235/75620172-2ee77780-5b64-11ea-988f-1e26d4004cea.png)
![image](https://user-images.githubusercontent.com/23153235/75620173-31e26800-5b64-11ea-927a-2d176274fba8.png)
E os campos aparecem duplicados na tela de cadastro de cliente:
![image](https://user-images.githubusercontent.com/23153235/75620180-46266500-5b64-11ea-8864-63848badf336.png)

Se eu coloco Show CPF e SHOW CNPJ para NO, não aparece os campos de CNPJ nem CPF obviamente, e nem o Radio Button para selecionar Person/Company.
Como deveria ser o comportamento normal nessas configurações? O usuário estará digitando no campo Tax/VatNumber o CPF ou CNPJ? e só muda o Label, Máscara e validações desse campo?
Mesmo  mudando de company para Person os campos CNPJ e CPF lá de baixo nunca mudam ou ficam escondidos (hidden) fica sempre como estão.
Estou testando o módulo na versão 2.3.4 do Magento nova somente com o SampleData

**Comment by eduardoddias** [comment]
Para o campo não ficar duplicado, no administrador altere:
Stores > Configuration > Customers > Customer Configuration > Name and Address Options > Show Tax/VAT Number

Para "No".

Sobre o segundo print, está marcado "Pessoa Física" e exibindo o campo CNPJ, verifica se não tem nenhum erro no console do Chrome, me parece erro de JS ou de tema.

Se estiver rodando modo produção tenta executar esses comandos:
bin/magento setup:static-content:deploy
bin/magento cache:clea

**Comment by rovae** [comment]
esta utilizando o firecheckout? estou com o mesmo problema

**Comment by JeffersonTeixeira** [comment]
> esta utilizando o firecheckout? estou com o mesmo problema

Sim, estou utilizando o Firecheckout (http://swissuplabs.com/)
Uma vez que na tela de checkout (com modo compra como visitante (guest checkout)) o módulo ainda não funciona eu preciso de usar a forma recomendada para adicionar o campo CPF/CNPJ conforme o link: https://docs.swissuplabs.com/m2/extensions/firecheckout/brazil/cpf-cnpj/ que usa o campo Vat.
Ou seja não posso desabilitar o Tax/Vat Number, a não ser que haja uma forma de forçar ele aparecer somente no checkout quando desabilitado no backend.
Estou pensando em criar um módulo provisório só para ter uma opção que caso a pessoa for se cadastrar tenha a opção de escolher PF ou PJ, adicionar uma máscara no VatNumber conforme o que a pessoa selecionar e deixar sem outros atributos: IE, RG, (campos separados para CPF e CNPJ) etc.

**Comment by eduardoddias** [comment]
Estou fechando essa issue por estar relacionado a bug com módulos não oficiais do Magento, oferecemos apenas suporte pago para esses casos, caso deseje entre em contato com a [SystemCode](https://www.systemcode.com.br/).
