### ISSUE TITLE
Alterar linhas utilizadas para Bairro e Complemento

### ISSUE THREAD

**Issue by ClaudioBlanco** [eduardoddias/Magento-SystemCode_BrazilCustomerAttributes#44]
Prezados,

Preciso alterar as linhas de endereço padrão onde o modulo grava o Bairro e o Complemento.

Atualmente está assim:
Complemento salvo na linha 4
Bairro salvo na linha 3

Preciso que seja o inverso:
Complemento na linha 3
Bairro na linha 4

Tem que ser alterado no código ou estou cego e não vendo a opção?

**Comment by rovae** [comment]
tem que ser alterado no código

**Comment by eduardoddias** [comment]
Duplicado

**Comment by andremc420** [comment]
@eduardoddias estou instalando o módulo em minha loja e deparei novamente com esse problema.

Qual é a solução para inverter os campos de bairro e complemento?
