### ISSUE TITLE
possibilidade de não criar atributos cpf/cnpj quando for copiar para o taxvat 

### ISSUE THREAD

**Issue by rovae** [eduardoddias/Magento-SystemCode_BrazilCustomerAttributes#45]
acredito que se a opção copiar cpf/cnpj para taxvat estiver marcada como sim, não seria necessário ter os atributtos cpf e cnpj preenchidos/criados

**Comment by eduardoddias** [comment]
A criação dos atributos é realizada na instalação do módulo, se fosse via configuração poderia ocorrer perda de dados acidental e acrescentaria uma complexidade alta no módulo. Portando não será implementado.
