### ISSUE TITLE
erro conflito número do Telefone 

### ISSUE THREAD

**Issue by marcelowu** [eduardoddias/Magento-SystemCode_BrazilCustomerAttributes#49]
![Screenshot from 2020-05-31 13-47-21](https://user-images.githubusercontent.com/30912144/83357835-4a217900-a345-11ea-8cef-5b87dcb2861d.png)

**Comment by MaxSouza** [comment]
@marcelowu o problema seria no tooltip? Qual versão do Magento? Precisamos de mais informações do problema.

**Comment by marcelowu** [comment]
versao Magento 2.3.5-p1 php7.3 ubuntu 20 nginx
