### ISSUE TITLE
Problemas ao remover o módulo

### ISSUE THREAD

**Issue by hugofernandocamargo** [eduardoddias/Magento-SystemCode_BrazilCustomerAttributes#5]
Boa noite,
Ao remover o módulo estou com o seguinte problema ao carregar a página de todos os clientes

1 exception(s):
Exception #0 (ReflectionException): Class SystemCode\BrazilCustomerAttributes\Model\Config\Source\Streetprefix does not exist

Exception #0 (ReflectionException): Class SystemCode\BrazilCustomerAttributes\Model\Config\Source\Streetprefix does not exist
#0 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/Code/Reader/ClassReader.php(19): ReflectionClass->__construct('SystemCode\\Braz...')
#1 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/ObjectManager/Definition/Runtime.php(44): Magento\Framework\Code\Reader\ClassReader->getConstructor('SystemCode\\Braz...')
#2 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/ObjectManager/Factory/Compiled.php(100): Magento\Framework\ObjectManager\Definition\Runtime->getParameters('SystemCode\\Braz...')
#3 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/ObjectManager/ObjectManager.php(56): Magento\Framework\ObjectManager\Factory\Compiled->create('SystemCode\\Braz...', Array)
#4 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/Validator/UniversalFactory.php(36): Magento\Framework\ObjectManager\ObjectManager->create('SystemCode\\Braz...', Array)
#5 /opt/bitnami/apps/magento/htdocs/vendor/magento/module-eav/Model/Entity/Attribute/AbstractAttribute.php(590): Magento\Framework\Validator\UniversalFactory->create('SystemCode\\Braz...')
#6 /opt/bitnami/apps/magento/htdocs/vendor/magento/module-customer/Model/AttributeMetadataConverter.php(68): Magento\Eav\Model\Entity\Attribute\AbstractAttribute->getSource()
#7 /opt/bitnami/apps/magento/htdocs/vendor/magento/module-customer/Model/Metadata/AddressMetadata.php(77): Magento\Customer\Model\AttributeMetadataConverter->createMetadataAttribute(Object(Magento\Customer\Model\Attribute))
#8 /opt/bitnami/apps/magento/htdocs/vendor/magento/module-customer/Model/Metadata/AddressMetadata.php(109): Magento\Customer\Model\Metadata\AddressMetadata->getAttributeMetadata('street_prefix')
#9 /opt/bitnami/apps/magento/htdocs/vendor/magento/module-customer/Model/Metadata/CachedMetadata.php(85): Magento\Customer\Model\Metadata\AddressMetadata->getAllAttributesMetadata()
#10 /opt/bitnami/apps/magento/htdocs/vendor/magento/module-customer/Ui/Component/Listing/AttributeRepository.php(85): Magento\Customer\Model\Metadata\CachedMetadata->getAllAttributesMetadata()
#11 /opt/bitnami/apps/magento/htdocs/vendor/magento/module-customer/Ui/Component/Listing/Columns.php(102): Magento\Customer\Ui\Component\Listing\AttributeRepository->getList()
#12 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/View/Layout/Generator/UiComponent.php(159): Magento\Customer\Ui\Component\Listing\Columns->prepare()
#13 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/View/Layout/Generator/UiComponent.php(156): Magento\Framework\View\Layout\Generator\UiComponent->prepareComponent(Object(Magento\Customer\Ui\Component\Listing\Columns))
#14 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/View/Layout/Generator/UiComponent.php(137): Magento\Framework\View\Layout\Generator\UiComponent->prepareComponent(Object(Magento\Ui\Component\Listing))
#15 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/View/Layout/Generator/UiComponent.php(97): Magento\Framework\View\Layout\Generator\UiComponent->generateComponent(Object(Magento\Framework\View\Layout\Data\Structure), 'customer_listin...', Array, Object(Magento\Framework\View\Layout\Interceptor))
#16 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/View/Layout/GeneratorPool.php(80): Magento\Framework\View\Layout\Generator\UiComponent->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#17 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/View/Layout.php(344): Magento\Framework\View\Layout\GeneratorPool->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#18 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/View/Layout/Builder.php(129): Magento\Framework\View\Layout->generateElements()
#19 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/View/Page/Builder.php(55): Magento\Framework\View\Layout\Builder->generateLayoutBlocks()
#20 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/View/Layout/Builder.php(65): Magento\Framework\View\Page\Builder->generateLayoutBlocks()
#21 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/View/Layout.php(254): Magento\Framework\View\Layout\Builder->build()
#22 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/View/Layout.php(875): Magento\Framework\View\Layout->build()
#23 /opt/bitnami/apps/magento/htdocs/vendor/magento/module-backend/Model/View/Result/Page.php(26): Magento\Framework\View\Layout->getBlock('menu')
#24 /opt/bitnami/apps/magento/htdocs/vendor/magento/module-customer/Controller/Adminhtml/Index/Index.php(26): Magento\Backend\Model\View\Result\Page->setActiveMenu('Magento_Custome...')
#25 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/App/Action/Action.php(107): Magento\Customer\Controller\Adminhtml\Index\Index->execute()
#26 /opt/bitnami/apps/magento/htdocs/vendor/magento/module-backend/App/AbstractAction.php(229): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#27 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#28 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Customer\Controller\Adminhtml\Index\Index\Interceptor->___callParent('dispatch', Array)
#29 /opt/bitnami/apps/magento/htdocs/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Customer\Controller\Adminhtml\Index\Index\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#30 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Customer\Controller\Adminhtml\Index\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#31 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Customer\Controller\Adminhtml\Index\Index\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#32 /opt/bitnami/apps/magento/htdocs/generated/code/Magento/Customer/Controller/Adminhtml/Index/Index/Interceptor.php(26): Magento\Customer\Controller\Adminhtml\Index\Index\Interceptor->___callPlugins('dispatch', Array, NULL)
#33 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/App/FrontController.php(55): Magento\Customer\Controller\Adminhtml\Index\Index\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#34 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#35 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#36 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#37 /opt/bitnami/apps/magento/htdocs/generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#38 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#39 /opt/bitnami/apps/magento/htdocs/vendor/magento/framework/App/Bootstrap.php(256): Magento\Framework\App\Http->launch()
#40 /opt/bitnami/apps/magento/htdocs/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))

Poderia me ajudar?

**Comment by hugofernandocamargo** [comment]
Resolvido deletando o atributo do cliente direto no banco.

**Comment by eduardoddias** [comment]
Na verdade precisava rodar no terminal os comandos:
php bin/magento setup:di:compile && php bin/magento setup:upgrade

Porque ele ainda estava procurando as classes do módulo.

**Comment by LuizSantos1** [comment]
@hugofernandocamargo @eduardoddias Tudo bem?
Eu testei esse módulo, desinstalei, limpei o módulo usando essa query: `DELETE FROM setup_module WHERE module='SystemCode_BrazilCustomerAttributes';` limpei cache, rodei php bin/magento setup:di:compile && php bin/magento setup:upgrade e ainda assim continuo tendo o erro:
SystemCode\BrazilCustomerAttributes\Model\Config\Source\Streetprefix does not exist 

Poderia me dizer como eliminar o atributo do cliente direto no banco de dados para ver se consigo resolver?

**Comment by hugofernandocamargo** [comment]
Boa noite, me arrume um acesso e eu te ajudo com o mesmo.

>

**Comment by LuizSantos1** [comment]
@hugofernandocamargo Não posso, é de um cliente. 
Se puder fale o que o senhor fez incluindo o código. 

Eu de momento, reinstalei o módulo e desativei, está tudo funcionando agora.

**Comment by mauricio-tonny** [comment]
@hugofernandocamargo para resolver o problema apague o atributo streetprefix da tabela eav_attribute direto do banco de dados, o correto era ao remover excluir os campos criados, porém não acontece com este módulo, sendo necessário intervenção manual. Espero ter ajudado !

**Comment by rafafl35** [comment]
Estou com o mesmo erro:
Magento 2.4.5 > PT-BR

1 exception(s):
Exception #0 (Magento\Framework\Exception\LocalizedException): Please upgrade your database: Run "bin/magento setup:upgrade" from the Magento root directory.
The following modules are outdated:
SystemCode_Base data: current version - none, required version - 1.0.0
SystemCode_BrazilCustomerAttributes data: current version - none, required version - 1.1.1

Exception #0 (Magento\Framework\Exception\LocalizedException): Please upgrade your database: Run "bin/magento setup:upgrade" from the Magento root directory.
The following modules are outdated:
SystemCode_Base data: current version - none, required version - 1.0.0
SystemCode_BrazilCustomerAttributes data: current version - none, required version - 1.1.1
<pre>#1 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#2 Magento\Framework\App\FrontController\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:23]
#3 Magento\Framework\App\FrontController\Interceptor->dispatch() called at [vendor/magento/framework/App/Http.php:116]
#4 Magento\Framework\App\Http->launch() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:23]
#5 Magento\Framework\App\Http\Interceptor->launch() called at [vendor/magento/framework/App/Bootstrap.php:264]
#6 Magento\Framework\App\Bootstrap->run() called at [pub/index.php:30]
</pre>

Alguém consegue me ajudar?
