### ISSUE TITLE
CPF/CNPJ não exibindo no Pedido

### ISSUE THREAD

**Issue by guiserinoli** [eduardoddias/Magento-SystemCode_BrazilCustomerAttributes#6]
Na página do pedido, consequentemente na página da fatura, o Taxvat Number não é exibido. Achava que era uma configuração de cliente da loja, porém acredito que não.

Como reproduzir:
Basta criar um pedido de testes e abrí-lo no Painel. O Taxvat number deveria estar na área de informações da conta, juntamente com o nome e email do cliente.

**Comment by eduardoddias** [comment]
@guiserinoli, na configuração do módulo, você setou pra copiar os campos CPF/CNPJ pro Taxvat?

**Comment by guiserinoli** [comment]
Sim, isto está sendo feito. Esse comportamento não acontecia antes dessa última atualização.
Apenas me confirme se não é realmente um comportamento esperado para repassarmos outras configurações ou até mesmo algum tipo de conflito com outros módulos.

**Comment by eduardoddias** [comment]
O módulo não faz a tratativa para mostrar o taxvat no pedido/fatura no admin. E pelo que vi, por padrão o Magento também não mostra, pode até ser uma melhoria futura.
