### ISSUE TITLE
Erro ao compilar - Magento 2.2.4

### ISSUE THREAD

**Issue by katiakweb** [eduardoddias/Magento-SystemCode_BrazilCustomerAttributes#7]
Compilação trava com a seguinte mensagem:
[RuntimeException]
  Class Magento\Framework\Serialize\SerializerInterface does not exist

Não aplica configurações no admin (impossível salvar) - mensagem de erro: "Something went wrong while saving this configuration: Class Magento\Framework\Serialize\SerializerInterface does not exist"

Read.me: qual os requisitos e compatibilidade do módulo?

**Comment by eduardoddias** [comment]
O ultimo commit foi testado nas versões 2.2.4 e 2.2.5

Encontrei isso na [documentação do Magento](https://devdocs.magento.com/guides/v2.2/extension-dev-guide/framework/serializer.html):

> Backward Compatibility Note
> 
> The SerializerInterface interface and its implementations only exist since Magento version 2.2.
> Because of this, it is not possible to use these classes in code that has to be compatible with Magento 2.1 or 2.0.

Por favor verfique se o arquivo abaixo existe:
vendor/magento/framework/Serialize/SerializerInterface.php

E so no /etc/di.xml consta:
`<preference for="Magento\Framework\Serialize\SerializerInterface" type="Magento\Framework\Serialize\Serializer\Json" />`

**Comment by eduardoddias** [comment]
Fechado por falta de replica, se necessário reabra a issue.

**Comment by zapcriativo** [comment]
Olá, verifiquei no magento 2.1 e não existe o arquivo citado por você.

Tem alguma forma de contornar isto?

Atenciosamente

**Comment by wurthmann** [comment]
Boa tarde

Alguém conseguiu resolver o problema? Na minha instalação do magento nem a pasta Serialize tem no diretório.

Fico no aguardo

**Comment by lobobruno** [comment]
Também estava com o erro, atualizei para a versão 2.2.5 e funcionou!!

bin/magento maintenance:enable
composer require magento/product-community-edition 2.2.5 --no-update
composer update
rm -rf var/cache/*
rm -rf var/page_cache/*
rm -rf var/generation/*
chmod +x bin/magento
bin/magento setup:upgrade
bin/magento maintenance:disable

php bin/magento setup:di:compile
php bin/magento setup:upgrade
